apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-deployment
  labels:
    app: jenkins-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: nginx:latest
        ports:
        - containerPort: 80
